/*
 * JOCLBLAS - Java bindings for clBLAS
 *
 * Copyright (c) 2015-2016 Marco Hutter - http://www.jocl.org
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jocl_blas_CLBLAS */

#ifndef _Included_org_jocl_blas_CLBLAS
#define _Included_org_jocl_blas_CLBLAS
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jocl_blas_CLBLAS_JOCL_BLAS_STATUS_INTERNAL_ERROR
#define org_jocl_blas_CLBLAS_JOCL_BLAS_STATUS_INTERNAL_ERROR -32786L
    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasGetVersionNative
    * Signature: ([I[I[I)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasGetVersionNative
        (JNIEnv *, jclass, jintArray, jintArray, jintArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSetupNative
    * Signature: ()I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSetupNative
        (JNIEnv *, jclass);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasTeardownNative
    * Signature: ()V
    */
    JNIEXPORT void JNICALL Java_org_jocl_blas_CLBLAS_clblasTeardownNative
        (JNIEnv *, jclass);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSswapNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSswapNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDswapNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDswapNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCswapNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCswapNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZswapNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZswapNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSscalNative
    * Signature: (JFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSscalNative
        (JNIEnv *, jclass, jlong, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDscalNative
    * Signature: (JDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDscalNative
        (JNIEnv *, jclass, jlong, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCscalNative
    * Signature: (J[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCscalNative
        (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZscalNative
    * Signature: (J[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZscalNative
        (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCsscalNative
    * Signature: (JFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCsscalNative
        (JNIEnv *, jclass, jlong, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZdscalNative
    * Signature: (JDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZdscalNative
        (JNIEnv *, jclass, jlong, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasScopyNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasScopyNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDcopyNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDcopyNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCcopyNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCcopyNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZcopyNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZcopyNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSaxpyNative
    * Signature: (JFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSaxpyNative
        (JNIEnv *, jclass, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDaxpyNative
    * Signature: (JDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDaxpyNative
        (JNIEnv *, jclass, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCaxpyNative
    * Signature: (J[FLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCaxpyNative
        (JNIEnv *, jclass, jlong, jfloatArray, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZaxpyNative
    * Signature: (J[DLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZaxpyNative
        (JNIEnv *, jclass, jlong, jdoubleArray, jobject, jlong, jint, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSdotNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSdotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDdotNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDdotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCdotuNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCdotuNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZdotuNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZdotuNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCdotcNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCdotcNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZdotcNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZdotcNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSrotgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSrotgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDrotgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDrotgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCrotgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCrotgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZrotgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZrotgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSrotmgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSrotmgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDrotmgNative
    * Signature: (Lorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDrotmgNative
        (JNIEnv *, jclass, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSrotNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JIFFI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSrotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jfloat, jfloat, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDrotNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JIDDI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDrotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jdouble, jdouble, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCsrotNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JIFFI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCsrotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jfloat, jfloat, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZdrotNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JIDDI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZdrotNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jdouble, jdouble, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSrotmNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSrotmNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDrotmNative
    * Signature: (JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDrotmNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSnrm2Native
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSnrm2Native
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDnrm2Native
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDnrm2Native
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasScnrm2Native
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasScnrm2Native
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDznrm2Native
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDznrm2Native
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasiSamaxNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasiSamaxNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasiDamaxNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasiDamaxNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasiCamaxNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasiCamaxNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasiZamaxNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasiZamaxNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSasumNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSasumNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDasumNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDasumNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasScasumNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasScasumNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDzasumNative
    * Signature: (JLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDzasumNative
        (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSgemvNative
    * Signature: (IIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSgemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jint, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDgemvNative
    * Signature: (IIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDgemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jint, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCgemvNative
    * Signature: (IIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCgemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jint, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZgemvNative
    * Signature: (IIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZgemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jint, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsymvNative
    * Signature: (IIJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsymvNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jint, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsymvNative
    * Signature: (IIJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsymvNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jint, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChemvNative
    * Signature: (IIJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jint, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhemvNative
    * Signature: (IIJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhemvNative
        (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jint, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStrmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStrmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtrmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtrmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtrmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtrmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtrmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtrmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStrsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStrsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtrsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtrsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtrsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtrsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtrsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtrsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSgerNative
    * Signature: (IJJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSgerNative
        (JNIEnv *, jclass, jint, jlong, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDgerNative
    * Signature: (IJJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDgerNative
        (JNIEnv *, jclass, jint, jlong, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCgeruNative
    * Signature: (IJJ[FLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCgeruNative
        (JNIEnv *, jclass, jint, jlong, jlong, jfloatArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZgeruNative
    * Signature: (IJJ[DLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZgeruNative
        (JNIEnv *, jclass, jint, jlong, jlong, jdoubleArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCgercNative
    * Signature: (IJJ[FLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCgercNative
        (JNIEnv *, jclass, jint, jlong, jlong, jfloatArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZgercNative
    * Signature: (IJJ[DLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZgercNative
        (JNIEnv *, jclass, jint, jlong, jlong, jdoubleArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsyrNative
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsyrNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsyrNative
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsyrNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCherNative
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCherNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZherNative
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZherNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsyr2Native
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsyr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsyr2Native
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsyr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCher2Native
    * Signature: (IIJ[FLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCher2Native
        (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZher2Native
    * Signature: (IIJ[DLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZher2Native
        (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStpmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStpmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtpmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtpmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtpmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtpmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtpmvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtpmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStpsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStpsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtpsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtpsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtpsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtpsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtpsvNative
    * Signature: (IIIIJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtpsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSspmvNative
    * Signature: (IIJFLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JIFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSspmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jobject, jlong, jint, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDspmvNative
    * Signature: (IIJDLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JIDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDspmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jobject, jlong, jint, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChpmvNative
    * Signature: (IIJ[FLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChpmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jobject, jlong, jint, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhpmvNative
    * Signature: (IIJ[DLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JI[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhpmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jobject, jlong, jint, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsprNative
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsprNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsprNative
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsprNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChprNative
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChprNative
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhprNative
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhprNative
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSspr2Native
    * Signature: (IIJFLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSspr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jfloat, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDspr2Native
    * Signature: (IIJDLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDspr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jdouble, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChpr2Native
    * Signature: (IIJ[FLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChpr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jfloatArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhpr2Native
    * Signature: (IIJ[DLorg/jocl/cl_mem;JILorg/jocl/cl_mem;JILorg/jocl/cl_mem;JI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhpr2Native
        (JNIEnv *, jclass, jint, jint, jlong, jdoubleArray, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSgbmvNative
    * Signature: (IIJJJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSgbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jint, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDgbmvNative
    * Signature: (IIJJJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDgbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jint, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCgbmvNative
    * Signature: (IIJJJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCgbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jint, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZgbmvNative
    * Signature: (IIJJJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZgbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jint, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStbmvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStbmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtbmvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtbmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtbmvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtbmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtbmvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JILorg/jocl/cl_mem;I[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtbmvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jobject, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsbmvNative
    * Signature: (IIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIFLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jint, jfloat, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsbmvNative
    * Signature: (IIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JIDLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jint, jdouble, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChbmvNative
    * Signature: (IIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[FLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jint, jfloatArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhbmvNative
    * Signature: (IIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JI[DLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhbmvNative
        (JNIEnv *, jclass, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jint, jdoubleArray, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStbsvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStbsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtbsvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtbsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtbsvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtbsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtbsvNative
    * Signature: (IIIIJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JII[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtbsvNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jint, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSgemmNative
    * Signature: (IIIJJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSgemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDgemmNative
    * Signature: (IIIJJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDgemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCgemmNative
    * Signature: (IIIJJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCgemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZgemmNative
    * Signature: (IIIJJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZgemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStrmmNative
    * Signature: (IIIIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStrmmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtrmmNative
    * Signature: (IIIIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtrmmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtrmmNative
    * Signature: (IIIIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtrmmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtrmmNative
    * Signature: (IIIIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtrmmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasStrsmNative
    * Signature: (IIIIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasStrsmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDtrsmNative
    * Signature: (IIIIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDtrsmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCtrsmNative
    * Signature: (IIIIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCtrsmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZtrsmNative
    * Signature: (IIIIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZtrsmNative
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsyrkNative
    * Signature: (IIIJJFLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsyrkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsyrkNative
    * Signature: (IIIJJDLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsyrkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCsyrkNative
    * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCsyrkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZsyrkNative
    * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZsyrkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsyr2kNative
    * Signature: (IIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsyr2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsyr2kNative
    * Signature: (IIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsyr2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCsyr2kNative
    * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCsyr2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZsyr2kNative
    * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZsyr2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasSsymmNative
    * Signature: (IIIJJFLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasSsymmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasDsymmNative
    * Signature: (IIIJJDLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasDsymmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCsymmNative
    * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCsymmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZsymmNative
    * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZsymmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasChemmNative
    * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[FLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasChemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloatArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZhemmNative
    * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJ[DLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZhemmNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCherkNative
    * Signature: (IIIJJFLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCherkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloat, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZherkNative
    * Signature: (IIIJJDLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZherkNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdouble, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCher2kNative
    * Signature: (IIIJJ[FLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJFLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCher2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jfloatArray, jobject, jlong, jlong, jobject, jlong, jlong, jfloat, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasZher2kNative
    * Signature: (IIIJJ[DLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJDLorg/jocl/cl_mem;JJI[Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasZher2kNative
        (JNIEnv *, jclass, jint, jint, jint, jlong, jlong, jdoubleArray, jobject, jlong, jlong, jobject, jlong, jlong, jdouble, jobject, jlong, jlong, jint, jobjectArray, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasMatrixSizeInfoNative
    * Signature: (IJJJJ[J[J)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasMatrixSizeInfoNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jlong, jlongArray, jlongArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCreateMatrixNative
    * Signature: (Lorg/jocl/cl_context;IJJJJ[J[J[I)Lorg/jocl/cl_mem;
    */
    JNIEXPORT jobject JNICALL Java_org_jocl_blas_CLBLAS_clblasCreateMatrixNative
        (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong, jlong, jlongArray, jlongArray, jintArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCreateMatrixWithLdNative
    * Signature: (Lorg/jocl/cl_context;IJJJJ[J[I)Lorg/jocl/cl_mem;
    */
    JNIEXPORT jobject JNICALL Java_org_jocl_blas_CLBLAS_clblasCreateMatrixWithLdNative
        (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong, jlong, jlongArray, jintArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCreateMatrixFromHostNative
    * Signature: (Lorg/jocl/cl_context;IJJJJLorg/jocl/Pointer;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[I)Lorg/jocl/cl_mem;
    */
    JNIEXPORT jobject JNICALL Java_org_jocl_blas_CLBLAS_clblasCreateMatrixFromHostNative
        (JNIEnv *, jclass, jobject, jint, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray, jintArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteSubMatrixNative
    * Signature: (IJLorg/jocl/Pointer;JJJJJJLorg/jocl/cl_mem;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteSubMatrixNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteSubMatrixAsyncNative
    * Signature: (IJLorg/jocl/Pointer;JJJJJJLorg/jocl/cl_mem;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteSubMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadSubMatrixNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJJJLorg/jocl/Pointer;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadSubMatrixNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadSubMatrixAsyncNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJJJLorg/jocl/Pointer;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadSubMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopySubMatrixNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJJJLorg/jocl/cl_mem;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopySubMatrixNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopySubMatrixAsyncNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJJJLorg/jocl/cl_mem;JJJJJJJJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopySubMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteVectorNative
    * Signature: (JJLorg/jocl/Pointer;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteVectorNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteVectorAsyncNative
    * Signature: (JJLorg/jocl/Pointer;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteVectorAsyncNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadVectorNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/Pointer;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadVectorNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadVectorAsyncNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/Pointer;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadVectorAsyncNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopyVectorNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopyVectorNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopyVectorAsyncNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/cl_mem;JLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopyVectorAsyncNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteMatrixNative
    * Signature: (IJJJLorg/jocl/Pointer;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteMatrixNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasWriteMatrixAsyncNative
    * Signature: (IJJJLorg/jocl/Pointer;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasWriteMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadMatrixNative
    * Signature: (IJJJLorg/jocl/cl_mem;JJLorg/jocl/Pointer;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadMatrixNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasReadMatrixAsyncNative
    * Signature: (IJJJLorg/jocl/cl_mem;JJLorg/jocl/Pointer;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasReadMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopyMatrixNative
    * Signature: (IJJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopyMatrixNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasCopyMatrixAsyncNative
    * Signature: (IJJJLorg/jocl/cl_mem;JJLorg/jocl/cl_mem;JJLorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasCopyMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jlong, jlong, jobject, jlong, jlong, jobject, jlong, jlong, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasFillVectorNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/Pointer;Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasFillVectorNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasFillVectorAsyncNative
    * Signature: (JJLorg/jocl/cl_mem;JLorg/jocl/Pointer;Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasFillVectorAsyncNative
        (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jobject, jint, jobjectArray, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasFillMatrixNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJLorg/jocl/Pointer;Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasFillMatrixNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jobject, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasFillSubMatrixNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJJJJJLorg/jocl/Pointer;Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasFillSubMatrixNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jobject, jobject, jint, jobjectArray);

    /*
    * Class:     org_jocl_blas_CLBLAS
    * Method:    clblasFillSubMatrixAsyncNative
    * Signature: (IJLorg/jocl/cl_mem;JJJJIIJJLorg/jocl/Pointer;Lorg/jocl/cl_command_queue;I[Lorg/jocl/cl_event;[Lorg/jocl/cl_event;)I
    */
    JNIEXPORT jint JNICALL Java_org_jocl_blas_CLBLAS_clblasFillSubMatrixAsyncNative
        (JNIEnv *, jclass, jint, jlong, jobject, jlong, jlong, jlong, jlong, jint, jint, jlong, jlong, jobject, jobject, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
